import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Union

from tools.misc import isnumeric


class SpaceGroups():

    def __init__(self):
        self.spgrps = {
            '1'  : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>1</mn>'
                    '</math>', 'P1'),
            '2'  : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>1</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'P-1'),
            '3'  : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>2</mn>'
                    '</math>', 'P2'),
            '4'  : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'P21'),
            '5'  : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>2</mn>'
                    '</math>', 'C2'),
            '6'  : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '</math>', 'Pm'),
            '7'  : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>c</mn>'
                    '</math>', 'Pc'),
            '8'  : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>m</mn>'
                    '</math>', 'Cm'),
            '9'  : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>c</mn>'
                    '</math>', 'Cc'),
            '10' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>2</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P2/m'),
            '11' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P21/m'),
            '12' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>2</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '</math>', 'C2/m'),
            '13' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>2</mn>'
                    '<mn>/</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P2/c'),
            '14' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P21/c'),
            '15' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>2</mn>'
                    '<mn>/</mn>'
                    '<mn>c</mn>'
                    '</math>', 'C2/c'),
            '16' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P222'),
            '17' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'P2221'),
            '18' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '</math>', 'P21212'),
            '19' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'P212121'),
            '20' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'C2221'),
            '21' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'C222'),
            '22' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'F222'),
            '23' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'I222'),
            '24' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'I212121'),
            '25' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Pmm2'),
            '26' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'Pmc21'),
            '27' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Pcc2'),
            '28' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mn>a</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Pma2'),
            '29' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>c</mn>'
                    '<mn>a</mn>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'Pca21'),
            '30' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>n</mn>'
                    '<mn>c</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Pnc2'),
            '31' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mn>n</mn>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'Pmn21'),
            '32' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>b</mn>'
                    '<mn>a</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Pba2'),
            '33' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>n</mn>'
                    '<mn>a</mn>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'Pna21'),
            '34' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>n</mn>'
                    '<mn>n</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Pnn2'),
            '35' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Cmm2'),
            '36' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'Cmc21'),
            '37' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Ccc2'),
            '38' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>A</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Amm2'),
            '39' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>A</mi>'
                    '<mn>e</mn>'
                    '<mn>m</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Aem2'),
            '40' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>A</mi>'
                    '<mn>m</mn>'
                    '<mn>a</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Ama2'),
            '41' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>A</mi>'
                    '<mn>e</mn>'
                    '<mn>a</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Aea2'),
            '42' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Fmm2'),
            '43' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>d</mn>'
                    '<mn>d</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Fdd2'),
            '44' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Imm2'),
            '45' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>b</mn>'
                    '<mn>a</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Iba2'),
            '46' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>m</mn>'
                    '<mn>a</mn>'
                    '<mn>2</mn>'
                    '</math>', 'Ima2'),
            '47' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Pmmm'),
            '48' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>n</mn>'
                    '<mn>n</mn>'
                    '<mn>n</mn>'
                    '</math>', 'Pnnn'),
            '49' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Pccm'),
            '50' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>b</mn>'
                    '<mn>a</mn>'
                    '<mn>n</mn>'
                    '</math>', 'Pban'),
            '51' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>a</mn>'
                    '</math>', 'Pmma'),
            '52' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>n</mn>'
                    '<mn>n</mn>'
                    '<mn>a</mn>'
                    '</math>', 'Pnna'),
            '53' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mn>n</mn>'
                    '<mn>a</mn>'
                    '</math>', 'Pmna'),
            '54' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '<mn>a</mn>'
                    '</math>', 'Pcca'),
            '55' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>b</mn>'
                    '<mn>a</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Pbam'),
            '56' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '<mn>n</mn>'
                    '</math>', 'Pccn'),
            '57' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>b</mn>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Pbcm'),
            '58' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>n</mn>'
                    '<mn>n</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Pnnm'),
            '59' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>n</mn>'
                    '</math>', 'Pmmn'),
            '60' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>b</mn>'
                    '<mn>c</mn>'
                    '<mn>n</mn>'
                    '</math>', 'Pbcn'),
            '61' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>b</mn>'
                    '<mn>c</mn>'
                    '<mn>a</mn>'
                    '</math>', 'Pbca'),
            '62' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>n</mn>'
                    '<mn>m</mn>'
                    '<mn>a</mn>'
                    '</math>', 'Pnma'),
            '63' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Cmcm'),
            '64' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '<mn>a</mn>'
                    '</math>', 'Cmca'),
            '65' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Cmmm'),
            '66' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Cccm'),
            '67' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>e</mn>'
                    '</math>', 'Cmme'),
            '68' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>C</mi>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '<mn>e</mn>'
                    '</math>', 'Ccce'),
            '69' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Fmmm'),
            '70' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>d</mn>'
                    '<mn>d</mn>'
                    '<mn>d</mn>'
                    '</math>', 'Fddd'),
            '71' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Immm'),
            '72' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>b</mn>'
                    '<mn>a</mn>'
                    '<mn>m</mn>'
                    '</math>', 'Ibam'),
            '73' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>b</mn>'
                    '<mn>c</mn>'
                    '<mn>a</mn>'
                    '</math>', 'Ibca'),
            '74' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>a</mn>'
                    '</math>', 'Imma'),
            '75' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '</math>', 'P4'),
            '76' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'P41'),
            '77' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '</math>', 'P42'),
            '78' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>3</mn>'
                    '</msub>'
                    '</math>', 'P43'),
            '79' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>4</mn>'
                    '</math>', 'I4'),
            '80' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'I41'),
            '81' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'P-4'),
            '82' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'I-4'),
            '83' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P4/m'),
            '84' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P42/m'),
            '85' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>n</mn>'
                    '</math>', 'P4/n'),
            '86' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>n</mn>'
                    '</math>', 'P42/n'),
            '87' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '</math>', 'I4/m'),
            '88' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>a</mn>'
                    '</math>', 'I41/a'),
            '89' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P422'),
            '90' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '</math>', 'P41212'),
            '91' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P4122'),
            '92' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '</math>', 'P41212'),
            '93' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P4222'),
            '94' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '</math>', 'P42212'),
            '95' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>3</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P4322'),
            '96' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>3</mn>'
                    '</msub>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '</math>', 'P43212'),
            '97' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'I422'),
            '98' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'I4122'),
            '99' : ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P4mm'),
            '100': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>b</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P4bm'),
            '101': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P42cm'),
            '102': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>n</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P42nm'),
            '103': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P4cc'),
            '104': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>n</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P4nc'),
            '105': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P42mc'),
            '106': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>b</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P42bc'),
            '107': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>4</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'I4mm'),
            '108': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>4</mn>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'I4cm'),
            '109': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>m</mn>'
                    '<mn>d</mn>'
                    '</math>', 'I41md'),
            '110': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>c</mn>'
                    '<mn>d</mn>'
                    '</math>', 'I42cd'),
            '111': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>2</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P-42m'),
            '112': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>2</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P-42c'),
            '113': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>m</mn>'
                    '</math>', 'P-421m'),
            '114': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>c</mn>'
                    '</math>', 'P-421c'),
            '115': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>m</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P-4m2'),
            '116': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>c</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P-4c2'),
            '117': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>b</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P-4b2'),
            '118': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>n</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P-4n2'),
            '119': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>m</mn>'
                    '<mn>2</mn>'
                    '</math>', 'I-4m2'),
            '120': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>c</mn>'
                    '<mn>2</mn>'
                    '</math>', 'I-4c2'),
            '121': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>2</mn>'
                    '<mn>m</mn>'
                    '</math>', 'I-42m'),
            '122': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>2</mn>'
                    '<mn>d</mn>'
                    '</math>', 'I-42d'),
            '123': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P4/mmm'),
            '124': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P4/mcc'),
            '125': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>n</mn>'
                    '<mn>b</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P4/nbm'),
            '126': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>n</mn>'
                    '<mn>n</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P4/nnc'),
            '127': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>b</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P4/mbm'),
            '128': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>n</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P4/mnc'),
            '129': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>n</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P4/nmm'),
            '130': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>n</mn>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P4/ncc'),
            '131': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P42/mmc'),
            '132': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P42/mcm'),
            '133': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>n</mn>'
                    '<mn>b</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P42/nbc'),
            '134': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>n</mn>'
                    '<mn>n</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P42/nnm'),
            '135': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>b</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P42/mbc'),
            '136': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>n</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P42/mnm'),
            '137': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>n</mn>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P42/nmc'),
            '138': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>n</mn>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P42/ncm'),
            '139': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'I4/mmm'),
            '140': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>4</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'I4/mcm'),
            '141': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>a</mn>'
                    '<mn>m</mn>'
                    '<mn>d</mn>'
                    '</math>', 'I41/amd'),
            '142': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>a</mn>'
                    '<mn>c</mn>'
                    '<mn>d</mn>'
                    '</math>', 'I41/acd'),
            #
            # trigonal
            #
            '143': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>3</mn>'
                    '</math>', 'P3'),
            '144': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>3</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'P31'),
            '145': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>3</mn>'
                    '<mn>3</mn>'
                    '</msub>'
                    '</math>', 'P33'),
            '146': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>R</mi>'
                    '<mn>3</mn>'
                    '</math>', 'R3'),
            '147': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'P-3'),
            '148': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>R</mi>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'R-3'),
            '149': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>3</mn>'
                    '<mn>1</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P312'),
            '150': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</math>', 'P321'),
            '151': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>3</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>1</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P3112'),
            '152': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>3</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</math>', 'P3121'),
            '153': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>1</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P3212'),
            '154': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</math>', 'P3221'),
            '155': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>R</mi>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</math>', 'R32'),
            '156': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>3</mn>'
                    '<mn>m</mn>'
                    '<mn>1</mn>'
                    '</math>', 'P3m1'),
            '157': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>3</mn>'
                    '<mn>1</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P31m'),
            '158': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>3</mn>'
                    '<mn>c</mn>'
                    '<mn>1</mn>'
                    '</math>', 'P3c1'),
            '159': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>3</mn>'
                    '<mn>1</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P31c'),
            '160': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>R</mi>'
                    '<mn>3</mn>'
                    '<mn>m</mn>'
                    '</math>', 'R3m'),
            '161': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>R</mi>'
                    '<mn>3</mn>'
                    '<mn>c</mn>'
                    '</math>', 'R3c'),
            '162': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>1</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P-31m'),
            '163': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>1</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P-31c'),
            '164': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>m</mn>'
                    '<mn>1</mn>'
                    '</math>', 'P-3m1'),
            '165': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>c</mn>'
                    '<mn>1</mn>'
                    '</math>', 'P-3c1'),
            '166': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>R</mi>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>m</mn>'
                    '</math>', 'R-3m'),
            '167': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>R</mi>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>c</mn>'
                    '</math>', 'R-3c'),
            '168': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>6</mn>'
                    '</math>', 'P6'),
            '169': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '</math>', 'P61'),
            '170': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>5</mn>'
                    '</msub>'
                    '</math>', 'P65'),
            '171': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '</math>', 'P62'),
            '172': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>4</mn>'
                    '</msub>'
                    '</math>', 'P64'),
            '173': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>3</mn>'
                    '</msub>'
                    '</math>', 'P63'),
            '174': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>6</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'P-6'),
            '175': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>6</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P6/m'),
            '176': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>3</mn>'
                    '</msub>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P63/m'),
            '177': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>6</mn>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P622'),
            '178': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P6122'),
            '179': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>5</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P6522'),
            '180': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P6222'),
            '181': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>4</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P6422'),
            '182': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>3</mn>'
                    '</msub>'
                    '<mn>2</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P6322'),
            '183': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>6</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P6mm'),
            '184': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>6</mn>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P6cc'),
            '185': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>3</mn>'
                    '</msub>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P63cm'),
            '186': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>6</mn>'
                    '<mn>3</mn>'
                    '</msub>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P63mc'),
            '187': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>6</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>m</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P-6m2'),
            '188': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>6</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>c</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P-6c2'),
            '189': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>6</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>2</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P-62m'),
            '190': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>6</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>2</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P-62c'),
            '191': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>6</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P6/mmm'),
            '192': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>6</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P6/mmc'),
            '193': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>6</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P6/mcm'),
            '194': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>6</mn>'
                    '<mn>/</mn>'
                    '<mn>m</mn>'
                    '<mn>m</mn>'
                    '<mn>c</mn>'
                    '</math>', 'P6/mmc'),
            '195': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>2</mn>'
                    '<mn>3</mn>'
                    '</math>', 'P23'),
            '196': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>2</mn>'
                    '<mn>3</mn>'
                    '</math>', 'F23'),
            '197': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>2</mn>'
                    '<mn>3</mn>'
                    '</math>', 'I23'),
            '198': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>3</mn>'
                    '</math>', 'P213'),
            '199': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<msub>'
                    '<mn>2</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>3</mn>'
                    '</math>', 'I213'),
            '200': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'Pm-3'),
            '201': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>n</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'Pn-3'),
            '202': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>m</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'Fm-3'),
            '203': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>d</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'Fd-3'),
            '204': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>m</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'Im-3'),
            '205': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>a</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'Pa-3'),
            '206': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>a</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '</math>', 'Ia-3'),
            '207': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>4</mn>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P432'),
            '208': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>2</mn>'
                    '</msub>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P4232'),
            '209': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>4</mn>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</math>', 'F432'),
            '210': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</math>', 'F4132'),
            '211': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>4</mn>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</math>', 'I432'),
            '212': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>3</mn>'
                    '</msub>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P4332'),
            '213': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</math>', 'P4132'),
            '214': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<msub>'
                    '<mn>4</mn>'
                    '<mn>1</mn>'
                    '</msub>'
                    '<mn>3</mn>'
                    '<mn>2</mn>'
                    '</math>', 'I4132'),
            '215': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>3</mn>'
                    '<mn>m</mn>'
                    '</math>', 'P-43m'),
            '216': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>3</mn>'
                    '<mn>m</mn>'
                    '</math>', 'F-43m'),
            '217': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>3</mn>'
                    '<mn>m</mn>'
                    '</math>', 'I-43m'),
            '218': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>3</mn>'
                    '<mn>n</mn>'
                    '</math>', 'P-43n'),
            '219': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>3</mn>'
                    '<mn>c</mn>'
                    '</math>', 'F-43c'),
            '220': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mover>'
                    '<mn>4</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>3</mn>'
                    '<mn>d</mn>'
                    '</math>', 'I-43d'),
            '221': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>m</mn>'
                    '</math>', 'Pm-3m'),
            '222': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>n</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>n</mn>'
                    '</math>', 'Pn-3n'),
            '223': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>m</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>n</mn>'
                    '</math>', 'Pm-3n'),
            '224': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>P</mi>'
                    '<mn>n</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>m</mn>'
                    '</math>', 'Pn-3m'),
            '225': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>m</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>m</mn>'
                    '</math>', 'Fm-3m'),
            '226': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>m</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>c</mn>'
                    '</math>', 'Fm-3c'),
            '227': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>d</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>m</mn>'
                    '</math>', 'Fd-3m'),
            '228': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>F</mi>'
                    '<mn>d</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>c</mn>'
                    '</math>', 'Fd-3c'),
            '229': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>m</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>m</mn>'
                    '</math>', 'Im-3m'),
            '230': ('<math xmlns="http://www.w3.org/1998/Math/MathML">'
                    '<mi>I</mi>'
                    '<mn>a</mn>'
                    '<mover>'
                    '<mn>3</mn>'
                    '<mo stretchy="false">&#x0305;</mo>'
                    '</mover>'
                    '<mn>d</mn>'
                    '</math>', 'Ia-3d'),
        }

    def iucrNumberToMathml(self, number: Union[int, str]) -> str:
        number = str(number)
        return self.spgrps[number][0]

    def iucrNumberToPlainText(self, number: Union[int, str]) -> str:
        number = str(number)
        return self.spgrps[number][1]

    def _to_html_without_body(self, number: Union[int, str]) -> str:
        """
        Retrurns the space group als html formated for rich-text Qt text fields. Overlined numbers seem
        not to be possible...

        >>> SpaceGroups().iucr_num_to_html(14)
        '<body><i>P</i>2<sub>1</sub>/c</body>'
        """
        num = str(number)
        mxml = self.spgrps.get(num)[0]
        root = ET.fromstring(mxml)
        txt = ''
        for root_element in root:
            substart = False
            if root_element.text:
                if root_element.tag.endswith('mi'):
                    txt = txt + "<i>{}</i>".format(root_element.text)
                elif root_element.tag.endswith('mn'):
                    if isnumeric(root_element.text) or root_element.text == '/':
                        txt = txt + root_element.text
                    else:
                        txt = txt + "<i>{}</i>".format(root_element.text)
            for sub_element in root_element:
                if sub_element.text:
                    if sub_element.tag.endswith('mo'):
                        # I do this shift, because the overline shifts from right to left ofer the number:
                        txt = '{}<span style=" text-decoration: overline;">{}</span>'.format(txt[:-1], txt[-1])
                    elif sub_element.tag.endswith('mn') and sub_element.text in ['1', '2', '3'] \
                            and root_element.tag.endswith('msub') and substart:
                        txt = txt + "<sub>{}</sub>".format(sub_element.text)
                    else:
                        txt = txt + sub_element.text
                        if root_element.tag.endswith('msub') and not substart:
                            substart = True
        return txt

    def iucr_num_to_html(self, number: Union[int, str]) -> str:
        txt = self._to_html_without_body(number)
        return '<body style="">{} &thinsp;({})</body>'.format(txt, number)


if __name__ == '__main__':
    s = SpaceGroups()
    txt = ''
    for n in range(1, 231):
        txt = txt + s.iucr_num_to_html(n) + '<br>\n'

    Path('testing.html').write_text(txt)
