#!/bin/bash

# Installs the required packages to run the Linux/MacOS application

python3.9 -m venv venv
source venv/bin/activate
venv/bin/python3.9 -m pip install pip -U

venv/bin/pip3 install -r requirements.txt
