twinning_dict = {'_twin_dimensionality': '<pre>\n'
                         '   The degree of overlap between the twin '
                         'lattices.  \n'
                         '   Most twin lattice symmetry (TLS) and twin lattice '
                         'quasi-symmetry (TLQS) \n'
                         '   twins as defined by Donnay and Donnay will be '
                         'triperiodic.  \n'
                         '\n'
                         '   Reference: Donnay, G. &amp; Donnay, J. D. H. '
                         '(1974). Can. Mineral. 12, 422-425. </pre>',
 '_twin_formation_mechanism': '<pre>\n'
                              '     A description of the method of twin '
                              'formation.</pre>',
 '_twin_individual_id': '<pre>\n'
                        '      The unique identifier for this twin '
                        'individual. \n'
                        '      The twin for which '
                        '_twin_individual_twin_matrix_\n'
                        '      is the identity matrix is called the reference '
                        'twin.  \n'
                        '      It is recommended that the reference twin be '
                        "labelled '1'. </pre>",
 '_twin_individual_mass_fraction_refined': '<pre>\n'
                                           '      The refined mass fraction of '
                                           'this twin individual; the sum\n'
                                           '      of all mass fractions must '
                                           'equal unity within the limits of \n'
                                           '      experimental '
                                           'uncertainty.</pre>',
 '_twin_individual_twin_lattice_type': '<pre>\n'
                                       '       Identification of the symmetry '
                                       'relationships between the \n'
                                       '       twin lattices as described in '
                                       'International Tables \n'
                                       '       for Crystallography (2004), '
                                       'Vol. C, Chapter 1.3.  \n'
                                       '       The twin with the identity '
                                       'matrix should be denoted as '
                                       "'ref'.</pre>",
 '_twin_individual_twin_matrix_11': '<pre>\n'
                                    '     Elements of the matrix U that '
                                    'multiplies the Miller indices h,k,l \n'
                                    '     of the reference twin to give the '
                                    "Miller indices h',k',l', \n"
                                    '     of the twin specified by '
                                    '_twin_individual_id \n'
                                    '\n'
                                    "          (h' k' l') = U (h k l )\n"
                                    '\n'
                                    '     It follows that the reference twin '
                                    'must have U = I, the identity matrix. '
                                    '</pre>',
 '_twin_individual_twin_matrix_12': '<pre>\n'
                                    '     Elements of the matrix U that '
                                    'multiplies the Miller indices h,k,l \n'
                                    '     of the reference twin to give the '
                                    "Miller indices h',k',l', \n"
                                    '     of the twin specified by '
                                    '_twin_individual_id \n'
                                    '\n'
                                    "          (h' k' l') = U (h k l )\n"
                                    '\n'
                                    '     It follows that the reference twin '
                                    'must have U = I, the identity matrix. '
                                    '</pre>',
 '_twin_individual_twin_matrix_13': '<pre>\n'
                                    '     Elements of the matrix U that '
                                    'multiplies the Miller indices h,k,l \n'
                                    '     of the reference twin to give the '
                                    "Miller indices h',k',l', \n"
                                    '     of the twin specified by '
                                    '_twin_individual_id \n'
                                    '\n'
                                    "          (h' k' l') = U (h k l )\n"
                                    '\n'
                                    '     It follows that the reference twin '
                                    'must have U = I, the identity matrix. '
                                    '</pre>',
 '_twin_individual_twin_matrix_21': '<pre>\n'
                                    '     Elements of the matrix U that '
                                    'multiplies the Miller indices h,k,l \n'
                                    '     of the reference twin to give the '
                                    "Miller indices h',k',l', \n"
                                    '     of the twin specified by '
                                    '_twin_individual_id \n'
                                    '\n'
                                    "          (h' k' l') = U (h k l )\n"
                                    '\n'
                                    '     It follows that the reference twin '
                                    'must have U = I, the identity matrix. '
                                    '</pre>',
 '_twin_individual_twin_matrix_22': '<pre>\n'
                                    '     Elements of the matrix U that '
                                    'multiplies the Miller indices h,k,l \n'
                                    '     of the reference twin to give the '
                                    "Miller indices h',k',l', \n"
                                    '     of the twin specified by '
                                    '_twin_individual_id \n'
                                    '\n'
                                    "          (h' k' l') = U (h k l )\n"
                                    '\n'
                                    '     It follows that the reference twin '
                                    'must have U = I, the identity matrix. '
                                    '</pre>',
 '_twin_individual_twin_matrix_23': '<pre>\n'
                                    '     Elements of the matrix U that '
                                    'multiplies the Miller indices h,k,l \n'
                                    '     of the reference twin to give the '
                                    "Miller indices h',k',l', \n"
                                    '     of the twin specified by '
                                    '_twin_individual_id \n'
                                    '\n'
                                    "          (h' k' l') = U (h k l )\n"
                                    '\n'
                                    '     It follows that the reference twin '
                                    'must have U = I, the identity matrix. '
                                    '</pre>',
 '_twin_individual_twin_matrix_31': '<pre>\n'
                                    '     Elements of the matrix U that '
                                    'multiplies the Miller indices h,k,l \n'
                                    '     of the reference twin to give the '
                                    "Miller indices h',k',l', \n"
                                    '     of the twin specified by '
                                    '_twin_individual_id \n'
                                    '\n'
                                    "          (h' k' l') = U (h k l )\n"
                                    '\n'
                                    '     It follows that the reference twin '
                                    'must have U = I, the identity matrix. '
                                    '</pre>',
 '_twin_individual_twin_matrix_32': '<pre>\n'
                                    '     Elements of the matrix U that '
                                    'multiplies the Miller indices h,k,l \n'
                                    '     of the reference twin to give the '
                                    "Miller indices h',k',l', \n"
                                    '     of the twin specified by '
                                    '_twin_individual_id \n'
                                    '\n'
                                    "          (h' k' l') = U (h k l )\n"
                                    '\n'
                                    '     It follows that the reference twin '
                                    'must have U = I, the identity matrix. '
                                    '</pre>',
 '_twin_individual_twin_matrix_33': '<pre>\n'
                                    '     Elements of the matrix U that '
                                    'multiplies the Miller indices h,k,l \n'
                                    '     of the reference twin to give the '
                                    "Miller indices h',k',l', \n"
                                    '     of the twin specified by '
                                    '_twin_individual_id \n'
                                    '\n'
                                    "          (h' k' l') = U (h k l )\n"
                                    '\n'
                                    '     It follows that the reference twin '
                                    'must have U = I, the identity matrix. '
                                    '</pre>',
 '_twin_morphology': '<pre>\n'
                     ' The physical relationship of the different twins to one '
                     'another.</pre>',
 '_twin_refln_F_squared_calc': '<pre> \n'
                               '\n'
                               '        Calculated value for the overall '
                               'squared structure factors (in\n'
                               '        electrons squared for X-ray '
                               'diffraction) arising from all \n'
                               '        the twin contributions to the peak '
                               'defined by _twin_refln_datum_id.  \n'
                               '        The total contribution from all twins '
                               'to a single observed\n'
                               '        reflection is modelled according to '
                               'the method of Pratt, Coyle\n'
                               '        and Ibers as follows:\n'
                               '\n'
                               '        _twin_refln_F_squared_calc = osf * Sum '
                               '(mf * _refln_F_squared_calc)\n'
                               '\n'
                               '        where osf is the overall scale '
                               'factor,\n'
                               '        mf is the mass fraction,\n'
                               '        and the sum is taken over all the twin '
                               'components that contribute\n'
                               '        to this diffraction peak.\n'
                               '\n'
                               '        Reference: Pratt, C. S., Coyle, B. A. '
                               '&amp; Ibers, J. A. (1971).\n'
                               '        J. Chem. Soc. A, pp. 2146-2151.</pre>',
 '_twin_refln_F_squared_calc_individual': '<pre> \n'
                                          '\n'
                                          '        Contribution of the twin '
                                          'identified by '
                                          '_twin_refln_individual_id \n'
                                          '        to '
                                          '_twin_refln_F_squared_calc. \n'
                                          '\n'
                                          '        '
                                          '_twin_refln_F_squared_calc_individual '
                                          '= osf * mf * _refln_F_squared_calc\n'
                                          '\n'
                                          '        where osf is the overall '
                                          'scale factor, mf is the mass '
                                          'factor.\n'
                                          '        For X-ray diffraction the '
                                          'units are electrons squared.\n'
                                          '</pre>',
 '_twin_refln_F_squared_meas': '<pre>\n'
                               '         The observed value F^2^ of the peak '
                               'referenced by \n'
                               '         _twin_refln_datum_id. This is '
                               'typically the observed peak\n'
                               '         intensity after Lorentz and '
                               'polarization corrections.</pre>',
 '_twin_refln_F_squared_sigma': '<pre>\n'
                                '            Standard uncertainty of '
                                '_twin_refln_F_squared_meas</pre>',
 '_twin_refln_datum_id': '<pre>\n'
                         '     This item serves to identify an observed '
                         'diffraction peak. \n'
                         '     It may include contributions from one or more '
                         'twin components\n'
                         '     and so may appear more than once in the '
                         'list.  \n'
                         '     The values of _twin_refln_F_squared_calc and \n'
                         '     _twin_refln_F_squared_meas indexed by\n'
                         '     _twin_refln_datum_id include the contributions '
                         'from all the twins.  \n'
                         '     The diffraction peak is indexed by \n'
                         '     _twin_refln_index_h, *_k and *_l referred to '
                         'the cell of \n'
                         '     the twin component identified by '
                         '_twin_refln_individual_id.  \n'
                         '     \n'
                         '     The list reference includes both '
                         '_twin_refln_datum_id and \n'
                         '     _twin_refln_individual_id.  The combination of '
                         'these two items \n'
                         '     may only appear once in a list. </pre>',
 '_twin_refln_include_status': '<pre>\n'
                               '    A symbol indicating how the reflection is '
                               'treated during refinement.</pre>',
 '_twin_refln_index_h': '<pre>\n'
                        '     Miller indices of a reflection from the twin '
                        'component \n'
                        '     labelled by _twin_refln_individual_id. \n'
                        '     The values of the Miller indices must '
                        'correspond \n'
                        '     to the cell defined for this twin component.  '
                        '</pre>',
 '_twin_refln_index_k': '<pre>\n'
                        '     Miller indices of a reflection from the twin '
                        'component \n'
                        '     labelled by _twin_refln_individual_id. \n'
                        '     The values of the Miller indices must '
                        'correspond \n'
                        '     to the cell defined for this twin component.  '
                        '</pre>',
 '_twin_refln_index_l': '<pre>\n'
                        '     Miller indices of a reflection from the twin '
                        'component \n'
                        '     labelled by _twin_refln_individual_id. \n'
                        '     The values of the Miller indices must '
                        'correspond \n'
                        '     to the cell defined for this twin component.  '
                        '</pre>',
 '_twin_refln_individual_id': '<pre>\n'
                              '      The unique identifier of the twin '
                              'individual \n'
                              '      whose Miller indices are given in '
                              '_twin_refln_index_.  \n'
                              '      The ID must match a _twin_individual_id '
                              'in the \n'
                              '      TWIN_INDIVIDUAL category.  \n'
                              '\n'
                              '     The list reference includes both '
                              '_twin_refln_datum_id and \n'
                              '     _twin_refln_individual_id.  The '
                              'combination of these two items \n'
                              '     may only appear once in a list. </pre>',
 '_twin_special_details': '<pre>\n'
                          '    Information about twinning in the sample not '
                          'contained in other data items.\n'
                          '\n'
                          'Example:\n'
                          '   Individuals 3 and 4 arise from form (I) '
                          'following an\n'
                          '    enantiotropic phase transition by sudden '
                          'cooling in\n'
                          '    a cryostat to 173K. </pre>'}