# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\GitHub\FinalCif\./gui\finalcif_gui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FinalCifWindow(object):
    def setupUi(self, FinalCifWindow):
        FinalCifWindow.setObjectName("FinalCifWindow")
        FinalCifWindow.resize(1097, 746)
        self.Mainwidget = QtWidgets.QWidget(FinalCifWindow)
        self.Mainwidget.setObjectName("Mainwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.Mainwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MercuryPushButton = QtWidgets.QPushButton(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MercuryPushButton.sizePolicy().hasHeightForWidth())
        self.MercuryPushButton.setSizePolicy(sizePolicy)
        self.MercuryPushButton.setObjectName("MercuryPushButton")
        self.gridLayout.addWidget(self.MercuryPushButton, 1, 1, 1, 1)
        self.CifFileGroupBox = QtWidgets.QGroupBox(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CifFileGroupBox.sizePolicy().hasHeightForWidth())
        self.CifFileGroupBox.setSizePolicy(sizePolicy)
        self.CifFileGroupBox.setObjectName("CifFileGroupBox")
        self.CifFileGridLayout = QtWidgets.QGridLayout(self.CifFileGroupBox)
        self.CifFileGridLayout.setObjectName("CifFileGridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.CifFileGroupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.CifFileGridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.CifFileGroupBox)
        self.pushButton.setObjectName("pushButton")
        self.CifFileGridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.CifFileGroupBox, 0, 1, 1, 1)
        self.DataFilesGroupBox = QtWidgets.QGroupBox(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.DataFilesGroupBox.sizePolicy().hasHeightForWidth())
        self.DataFilesGroupBox.setSizePolicy(sizePolicy)
        self.DataFilesGroupBox.setObjectName("DataFilesGroupBox")
        self.DataSourcesGridLayout = QtWidgets.QGridLayout(self.DataFilesGroupBox)
        self.DataSourcesGridLayout.setObjectName("DataSourcesGridLayout")
        self.DataFileEdit = QtWidgets.QLineEdit(self.DataFilesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataFileEdit.sizePolicy().hasHeightForWidth())
        self.DataFileEdit.setSizePolicy(sizePolicy)
        self.DataFileEdit.setObjectName("DataFileEdit")
        self.DataSourcesGridLayout.addWidget(self.DataFileEdit, 1, 1, 1, 1)
        self.DataFileLabel = QtWidgets.QLabel(self.DataFilesGroupBox)
        self.DataFileLabel.setObjectName("DataFileLabel")
        self.DataSourcesGridLayout.addWidget(self.DataFileLabel, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.DataSourcesGridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.DataFileButton = QtWidgets.QPushButton(self.DataFilesGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DataFileButton.sizePolicy().hasHeightForWidth())
        self.DataFileButton.setSizePolicy(sizePolicy)
        self.DataFileButton.setObjectName("DataFileButton")
        self.DataSourcesGridLayout.addWidget(self.DataFileButton, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.DataFilesGroupBox, 9, 1, 1, 1)
        self.CifDataItemsGroupBox = QtWidgets.QGroupBox(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CifDataItemsGroupBox.sizePolicy().hasHeightForWidth())
        self.CifDataItemsGroupBox.setSizePolicy(sizePolicy)
        self.CifDataItemsGroupBox.setObjectName("CifDataItemsGroupBox")
        self.CifTableGridLayout = QtWidgets.QGridLayout(self.CifDataItemsGroupBox)
        self.CifTableGridLayout.setObjectName("CifTableGridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.CifTableGridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.SaveResidualsTableButton = QtWidgets.QPushButton(self.CifDataItemsGroupBox)
        self.SaveResidualsTableButton.setObjectName("SaveResidualsTableButton")
        self.CifTableGridLayout.addWidget(self.SaveResidualsTableButton, 2, 1, 1, 1)
        self.SaveFullReportButton = QtWidgets.QPushButton(self.CifDataItemsGroupBox)
        self.SaveFullReportButton.setObjectName("SaveFullReportButton")
        self.CifTableGridLayout.addWidget(self.SaveFullReportButton, 2, 2, 1, 1)
        self.CifItemsTable = QtWidgets.QTableWidget(self.CifDataItemsGroupBox)
        self.CifItemsTable.setMidLineWidth(0)
        self.CifItemsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.CifItemsTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.CifItemsTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.CifItemsTable.setObjectName("CifItemsTable")
        self.CifItemsTable.setColumnCount(3)
        self.CifItemsTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.CifItemsTable.setItem(4, 0, item)
        self.CifItemsTable.horizontalHeader().setDefaultSectionSize(152)
        self.CifItemsTable.horizontalHeader().setHighlightSections(False)
        self.CifItemsTable.horizontalHeader().setMinimumSectionSize(80)
        self.CifItemsTable.verticalHeader().setDefaultSectionSize(23)
        self.CifItemsTable.verticalHeader().setMinimumSectionSize(19)
        self.CifTableGridLayout.addWidget(self.CifItemsTable, 0, 0, 1, 3)
        self.SaveCifButton = QtWidgets.QPushButton(self.CifDataItemsGroupBox)
        self.SaveCifButton.setObjectName("SaveCifButton")
        self.CifTableGridLayout.addWidget(self.SaveCifButton, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.CifTableGridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.CifDataItemsGroupBox, 0, 2, 10, 1)
        self.groupBox = QtWidgets.QGroupBox(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TemplatesStackedWidget = QtWidgets.QStackedWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.TemplatesStackedWidget.sizePolicy().hasHeightForWidth())
        self.TemplatesStackedWidget.setSizePolicy(sizePolicy)
        self.TemplatesStackedWidget.setObjectName("TemplatesStackedWidget")
        self.TemplatesStackedWidgetPage1 = QtWidgets.QWidget()
        self.TemplatesStackedWidgetPage1.setObjectName("TemplatesStackedWidgetPage1")
        self.TemplatesGridLayout = QtWidgets.QGridLayout(self.TemplatesStackedWidgetPage1)
        self.TemplatesGridLayout.setObjectName("TemplatesGridLayout")
        self.EditTemplateButton = QtWidgets.QPushButton(self.TemplatesStackedWidgetPage1)
        self.EditTemplateButton.setObjectName("EditTemplateButton")
        self.TemplatesGridLayout.addWidget(self.EditTemplateButton, 1, 1, 1, 1)
        self.NewTemplateButton = QtWidgets.QPushButton(self.TemplatesStackedWidgetPage1)
        self.NewTemplateButton.setObjectName("NewTemplateButton")
        self.TemplatesGridLayout.addWidget(self.NewTemplateButton, 1, 0, 1, 1)
        self.TemplatesListWidget = QtWidgets.QListWidget(self.TemplatesStackedWidgetPage1)
        self.TemplatesListWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TemplatesListWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TemplatesListWidget.setObjectName("TemplatesListWidget")
        item = QtWidgets.QListWidgetItem()
        self.TemplatesListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.TemplatesListWidget.addItem(item)
        self.TemplatesGridLayout.addWidget(self.TemplatesListWidget, 0, 0, 1, 2)
        self.TemplatesStackedWidget.addWidget(self.TemplatesStackedWidgetPage1)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.page)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 2)
        self.TemplatesStackedWidget.addWidget(self.page)
        self.gridLayout_3.addWidget(self.TemplatesStackedWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.Mainwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.TemplatesStackedWidget_2 = QtWidgets.QStackedWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.TemplatesStackedWidget_2.sizePolicy().hasHeightForWidth())
        self.TemplatesStackedWidget_2.setSizePolicy(sizePolicy)
        self.TemplatesStackedWidget_2.setObjectName("TemplatesStackedWidget_2")
        self.TemplatesStackedWidgetPage1_2 = QtWidgets.QWidget()
        self.TemplatesStackedWidgetPage1_2.setObjectName("TemplatesStackedWidgetPage1_2")
        self.TemplatesGridLayout_2 = QtWidgets.QGridLayout(self.TemplatesStackedWidgetPage1_2)
        self.TemplatesGridLayout_2.setObjectName("TemplatesGridLayout_2")
        self.NewTemplateButton_2 = QtWidgets.QPushButton(self.TemplatesStackedWidgetPage1_2)
        self.NewTemplateButton_2.setObjectName("NewTemplateButton_2")
        self.TemplatesGridLayout_2.addWidget(self.NewTemplateButton_2, 1, 0, 1, 1)
        self.TemplatesListWidget_2 = QtWidgets.QListWidget(self.TemplatesStackedWidgetPage1_2)
        self.TemplatesListWidget_2.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TemplatesListWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TemplatesListWidget_2.setObjectName("TemplatesListWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.TemplatesListWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.TemplatesListWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.TemplatesListWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.TemplatesListWidget_2.addItem(item)
        self.TemplatesGridLayout_2.addWidget(self.TemplatesListWidget_2, 0, 0, 1, 2)
        self.EditTemplateButton_2 = QtWidgets.QPushButton(self.TemplatesStackedWidgetPage1_2)
        self.EditTemplateButton_2.setObjectName("EditTemplateButton_2")
        self.TemplatesGridLayout_2.addWidget(self.EditTemplateButton_2, 1, 1, 1, 1)
        self.TemplatesStackedWidget_2.addWidget(self.TemplatesStackedWidgetPage1_2)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_5.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.page_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_2.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_5.addWidget(self.tableWidget_2, 0, 0, 1, 2)
        self.TemplatesStackedWidget_2.addWidget(self.page_2)
        self.gridLayout_4.addWidget(self.TemplatesStackedWidget_2, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_2, 6, 1, 1, 1)
        FinalCifWindow.setCentralWidget(self.Mainwidget)
        self.actionSave_Report = QtWidgets.QAction(FinalCifWindow)
        self.actionSave_Report.setObjectName("actionSave_Report")
        self.actionSave_CIF_File = QtWidgets.QAction(FinalCifWindow)
        self.actionSave_CIF_File.setObjectName("actionSave_CIF_File")
        self.actionedit_templates = QtWidgets.QAction(FinalCifWindow)
        self.actionedit_templates.setObjectName("actionedit_templates")

        self.retranslateUi(FinalCifWindow)
        self.TemplatesStackedWidget.setCurrentIndex(0)
        self.TemplatesStackedWidget_2.setCurrentIndex(0)
        self.EditTemplateButton.clicked.connect(self.EditTemplateButton.click)
        QtCore.QMetaObject.connectSlotsByName(FinalCifWindow)

    def retranslateUi(self, FinalCifWindow):
        _translate = QtCore.QCoreApplication.translate
        FinalCifWindow.setWindowTitle(_translate("FinalCifWindow", "FinalCif"))
        self.MercuryPushButton.setText(_translate("FinalCifWindow", "View in Mercury"))
        self.CifFileGroupBox.setTitle(_translate("FinalCifWindow", "Cif file"))
        self.lineEdit.setText(_translate("FinalCifWindow", "C:\\frames\\guest\\foo\\work\\bar.cif"))
        self.pushButton.setText(_translate("FinalCifWindow", "Select File"))
        self.DataFilesGroupBox.setTitle(_translate("FinalCifWindow", "Data Sources"))
        self.DataFileEdit.setPlaceholderText(_translate("FinalCifWindow", " .abs file from SADABS"))
        self.DataFileLabel.setText(_translate("FinalCifWindow", "SADABS"))
        self.DataFileButton.setText(_translate("FinalCifWindow", "Select File"))
        self.CifDataItemsGroupBox.setTitle(_translate("FinalCifWindow", "Missing CIF Items"))
        self.SaveResidualsTableButton.setText(_translate("FinalCifWindow", "CheckCif"))
        self.SaveFullReportButton.setText(_translate("FinalCifWindow", "Save Report"))
        item = self.CifItemsTable.verticalHeaderItem(0)
        item.setText(_translate("FinalCifWindow", "_ls_refine_foo_bar"))
        item = self.CifItemsTable.verticalHeaderItem(1)
        item.setText(_translate("FinalCifWindow", "_exptl_absorpt_correction_T_max"))
        item = self.CifItemsTable.verticalHeaderItem(2)
        item.setText(_translate("FinalCifWindow", "_exptl_crystal_size_min"))
        item = self.CifItemsTable.verticalHeaderItem(3)
        item.setText(_translate("FinalCifWindow", "_diffrn_reflns_limit_l_max"))
        item = self.CifItemsTable.verticalHeaderItem(4)
        item.setText(_translate("FinalCifWindow", "_diffrn_ambient_temperature"))
        item = self.CifItemsTable.horizontalHeaderItem(0)
        item.setText(_translate("FinalCifWindow", "CIF Value"))
        item = self.CifItemsTable.horizontalHeaderItem(1)
        item.setText(_translate("FinalCifWindow", "From Data Source"))
        item = self.CifItemsTable.horizontalHeaderItem(2)
        item.setText(_translate("FinalCifWindow", "Own Data"))
        __sortingEnabled = self.CifItemsTable.isSortingEnabled()
        self.CifItemsTable.setSortingEnabled(False)
        item = self.CifItemsTable.item(0, 0)
        item.setText(_translate("FinalCifWindow", "foo"))
        item = self.CifItemsTable.item(0, 2)
        item.setText(_translate("FinalCifWindow", "bar"))
        item = self.CifItemsTable.item(1, 0)
        item.setText(_translate("FinalCifWindow", "?"))
        item = self.CifItemsTable.item(1, 1)
        item.setText(_translate("FinalCifWindow", "0.876"))
        item = self.CifItemsTable.item(2, 0)
        item.setText(_translate("FinalCifWindow", "?"))
        item = self.CifItemsTable.item(2, 2)
        item.setText(_translate("FinalCifWindow", "0.1"))
        item = self.CifItemsTable.item(3, 0)
        item.setText(_translate("FinalCifWindow", "13"))
        item = self.CifItemsTable.item(4, 0)
        item.setText(_translate("FinalCifWindow", "100"))
        self.CifItemsTable.setSortingEnabled(__sortingEnabled)
        self.SaveCifButton.setText(_translate("FinalCifWindow", "Save Cif File"))
        self.groupBox.setTitle(_translate("FinalCifWindow", "Equipment Templates"))
        self.EditTemplateButton.setText(_translate("FinalCifWindow", "Edit Template"))
        self.NewTemplateButton.setText(_translate("FinalCifWindow", "New Template"))
        __sortingEnabled = self.TemplatesListWidget.isSortingEnabled()
        self.TemplatesListWidget.setSortingEnabled(False)
        item = self.TemplatesListWidget.item(0)
        item.setText(_translate("FinalCifWindow", "Bruker D8 VENTURE"))
        item = self.TemplatesListWidget.item(1)
        item.setText(_translate("FinalCifWindow", "Bruker SMART APEXII QUAZAR"))
        self.TemplatesListWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("FinalCifWindow", "Save"))
        self.pushButton_3.setText(_translate("FinalCifWindow", "Delete"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FinalCifWindow", "Key"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FinalCifWindow", "Value"))
        self.groupBox_2.setTitle(_translate("FinalCifWindow", "Properties Templates"))
        self.NewTemplateButton_2.setText(_translate("FinalCifWindow", "New Template"))
        __sortingEnabled = self.TemplatesListWidget_2.isSortingEnabled()
        self.TemplatesListWidget_2.setSortingEnabled(False)
        item = self.TemplatesListWidget_2.item(0)
        item.setText(_translate("FinalCifWindow", "Crystal Color"))
        item = self.TemplatesListWidget_2.item(1)
        item.setText(_translate("FinalCifWindow", "Crystal Habit"))
        item = self.TemplatesListWidget_2.item(2)
        item.setText(_translate("FinalCifWindow", "Hans Meister"))
        item = self.TemplatesListWidget_2.item(3)
        item.setText(_translate("FinalCifWindow", "Temperatures"))
        self.TemplatesListWidget_2.setSortingEnabled(__sortingEnabled)
        self.EditTemplateButton_2.setText(_translate("FinalCifWindow", "Edit Template"))
        self.pushButton_4.setText(_translate("FinalCifWindow", "Save"))
        self.pushButton_5.setText(_translate("FinalCifWindow", "Delete"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("FinalCifWindow", "Key"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("FinalCifWindow", "Value"))
        self.actionSave_Report.setText(_translate("FinalCifWindow", "Save Report"))
        self.actionSave_CIF_File.setText(_translate("FinalCifWindow", "Save CIF File"))
        self.actionedit_templates.setText(_translate("FinalCifWindow", "edit templates"))


