# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_selector_ui.ui'
#
# Created by: PyQt5 UI code generator#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_importSelectMainWindow(object):
    def setupUi(self, importSelectMainWindow):
        importSelectMainWindow.setObjectName("importSelectMainWindow")
        importSelectMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(importSelectMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.importInfoLabel = QtWidgets.QLabel(self.centralwidget)
        self.importInfoLabel.setText("")
        self.importInfoLabel.setObjectName("importInfoLabel")
        self.verticalLayout.addWidget(self.importInfoLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, 10, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.importTable_keys = QtWidgets.QTableWidget(self.centralwidget)
        self.importTable_keys.setObjectName("importTable_keys")
        self.importTable_keys.setColumnCount(1)
        self.importTable_keys.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.importTable_keys.setHorizontalHeaderItem(0, item)
        self.importTable_keys.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.importTable_keys)
        self.importTable_loops = QtWidgets.QTableWidget(self.centralwidget)
        self.importTable_loops.setObjectName("importTable_loops")
        self.importTable_loops.setColumnCount(1)
        self.importTable_loops.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.importTable_loops.setHorizontalHeaderItem(0, item)
        self.importTable_loops.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.importTable_loops)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.importSelectedPushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.importSelectedPushbutton.setObjectName("importSelectedPushbutton")
        self.horizontalLayout.addWidget(self.importSelectedPushbutton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.selectOnlyNewPB = QtWidgets.QPushButton(self.centralwidget)
        self.selectOnlyNewPB.setObjectName("selectOnlyNewPB")
        self.horizontalLayout.addWidget(self.selectOnlyNewPB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.saveSelectionPushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.saveSelectionPushbutton.setObjectName("saveSelectionPushbutton")
        self.horizontalLayout.addWidget(self.saveSelectionPushbutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        importSelectMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(importSelectMainWindow)
        QtCore.QMetaObject.connectSlotsByName(importSelectMainWindow)

    def retranslateUi(self, importSelectMainWindow):
        _translate = QtCore.QCoreApplication.translate
        importSelectMainWindow.setWindowTitle(_translate("importSelectMainWindow", "Select import items"))
        item = self.importTable_keys.horizontalHeaderItem(0)
        item.setText(_translate("importSelectMainWindow", "keys"))
        item = self.importTable_loops.horizontalHeaderItem(0)
        item.setText(_translate("importSelectMainWindow", "loops"))
        self.importSelectedPushbutton.setText(_translate("importSelectMainWindow", "Import Selected"))
        self.selectOnlyNewPB.setText(_translate("importSelectMainWindow", "Select Only New Data"))
        self.saveSelectionPushbutton.setText(_translate("importSelectMainWindow", "Save current Selection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    importSelectMainWindow = QtWidgets.QMainWindow()
    ui = Ui_importSelectMainWindow()
    ui.setupUi(importSelectMainWindow)
    importSelectMainWindow.show()
    sys.exit(app.exec_())
