# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_selector_ui.ui'
#
# Created by: PyQt5 UI code generator#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_importSelectMainWindow(object):
    def setupUi(self, importSelectMainWindow):
        importSelectMainWindow.setObjectName("importSelectMainWindow")
        importSelectMainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(importSelectMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.importInfoLabel = QtWidgets.QLabel(self.centralwidget)
        self.importInfoLabel.setText("")
        self.importInfoLabel.setObjectName("importInfoLabel")
        self.verticalLayout.addWidget(self.importInfoLabel)
        self.importTable = QtWidgets.QTableWidget(self.centralwidget)
        self.importTable.setObjectName("importTable")
        self.importTable.setColumnCount(1)
        self.importTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.importTable.setHorizontalHeaderItem(0, item)
        self.importTable.horizontalHeader().setVisible(False)
        self.importTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.importTable)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.importSelectedPushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.importSelectedPushbutton.setObjectName("importSelectedPushbutton")
        self.horizontalLayout.addWidget(self.importSelectedPushbutton)
        self.saveSelectionPushbutton = QtWidgets.QPushButton(self.centralwidget)
        self.saveSelectionPushbutton.setObjectName("saveSelectionPushbutton")
        self.horizontalLayout.addWidget(self.saveSelectionPushbutton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        importSelectMainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(importSelectMainWindow)
        QtCore.QMetaObject.connectSlotsByName(importSelectMainWindow)

    def retranslateUi(self, importSelectMainWindow):
        _translate = QtCore.QCoreApplication.translate
        importSelectMainWindow.setWindowTitle(_translate("importSelectMainWindow", "Select import items"))
        item = self.importTable.horizontalHeaderItem(0)
        item.setText(_translate("importSelectMainWindow", "keys"))
        self.importSelectedPushbutton.setText(_translate("importSelectMainWindow", "Import Selected"))
        self.saveSelectionPushbutton.setText(_translate("importSelectMainWindow", "Save current Selection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    importSelectMainWindow = QtWidgets.QMainWindow()
    ui = Ui_importSelectMainWindow()
    ui.setupUi(importSelectMainWindow)
    importSelectMainWindow.show()
    sys.exit(app.exec_())
