# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/daniel/Documents/GitHub/FinalCif/finalcif/gui/text_templates.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TextTemplatesWidget(object):
    def setupUi(self, TextTemplatesWidget):
        TextTemplatesWidget.setObjectName("TextTemplatesWidget")
        TextTemplatesWidget.resize(765, 658)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(TextTemplatesWidget)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(6, -1, -1, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(TextTemplatesWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(TextTemplatesWidget)
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.combinedTestGroupBox = QtWidgets.QGroupBox(TextTemplatesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.combinedTestGroupBox.sizePolicy().hasHeightForWidth())
        self.combinedTestGroupBox.setSizePolicy(sizePolicy)
        self.combinedTestGroupBox.setObjectName("combinedTestGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.combinedTestGroupBox)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.combinedTestGroupBox)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_4.addWidget(self.plainTextEdit)
        self.verticalLayout_3.addWidget(self.combinedTestGroupBox)
        self.TemplatesListGroupBox = QtWidgets.QGroupBox(TextTemplatesWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.TemplatesListGroupBox.sizePolicy().hasHeightForWidth())
        self.TemplatesListGroupBox.setSizePolicy(sizePolicy)
        self.TemplatesListGroupBox.setObjectName("TemplatesListGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.TemplatesListGroupBox)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.TemplatesListGroupBox)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.exportTextPushButton = QtWidgets.QPushButton(self.TemplatesListGroupBox)
        self.exportTextPushButton.setObjectName("exportTextPushButton")
        self.horizontalLayout_3.addWidget(self.exportTextPushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.TemplatesListGroupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backToCIFfromTextButton = QtWidgets.QPushButton(TextTemplatesWidget)
        self.backToCIFfromTextButton.setObjectName("backToCIFfromTextButton")
        self.horizontalLayout_2.addWidget(self.backToCIFfromTextButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.applyTextPushButton = QtWidgets.QPushButton(TextTemplatesWidget)
        self.applyTextPushButton.setObjectName("applyTextPushButton")
        self.horizontalLayout_2.addWidget(self.applyTextPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(TextTemplatesWidget)
        QtCore.QMetaObject.connectSlotsByName(TextTemplatesWidget)

    def retranslateUi(self, TextTemplatesWidget):
        _translate = QtCore.QCoreApplication.translate
        TextTemplatesWidget.setWindowTitle(_translate("TextTemplatesWidget", "TextTemplatesWidget"))
        self.label.setText(_translate("TextTemplatesWidget", "CIF key:"))
        self.combinedTestGroupBox.setTitle(_translate("TextTemplatesWidget", "Combined text"))
        self.plainTextEdit.setPlaceholderText(_translate("TextTemplatesWidget", "The text of the selected templates is added her in selection order"))
        self.TemplatesListGroupBox.setTitle(_translate("TextTemplatesWidget", "Select one or more templates"))
        self.exportTextPushButton.setText(_translate("TextTemplatesWidget", "Export Templates"))
        self.backToCIFfromTextButton.setText(_translate("TextTemplatesWidget", "Back to CIF Table"))
        self.applyTextPushButton.setText(_translate("TextTemplatesWidget", "Apply Text"))
