# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/daniel/Documents/GitHub/FinalCif/finalcif/gui/text_templates.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_text_templates_window(object):
    def setupUi(self, text_templates_window):
        text_templates_window.setObjectName("text_templates_window")
        text_templates_window.resize(753, 658)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(text_templates_window)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(text_templates_window)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(text_templates_window)
        self.lineEdit.setText("")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.combinedTestGroupBox = QtWidgets.QGroupBox(text_templates_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.combinedTestGroupBox.sizePolicy().hasHeightForWidth())
        self.combinedTestGroupBox.setSizePolicy(sizePolicy)
        self.combinedTestGroupBox.setObjectName("combinedTestGroupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.combinedTestGroupBox)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.combinedTestGroupBox)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_4.addWidget(self.plainTextEdit)
        self.verticalLayout_3.addWidget(self.combinedTestGroupBox)
        self.TemplatesListGroupBox = QtWidgets.QGroupBox(text_templates_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.TemplatesListGroupBox.sizePolicy().hasHeightForWidth())
        self.TemplatesListGroupBox.setSizePolicy(sizePolicy)
        self.TemplatesListGroupBox.setObjectName("TemplatesListGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.TemplatesListGroupBox)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget = QtWidgets.QListWidget(self.TemplatesListGroupBox)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.moreTemplatesVLayout = QtWidgets.QVBoxLayout()
        self.moreTemplatesVLayout.setObjectName("moreTemplatesVLayout")
        self.moreTemplatesPushButton = QtWidgets.QPushButton(self.TemplatesListGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moreTemplatesPushButton.sizePolicy().hasHeightForWidth())
        self.moreTemplatesPushButton.setSizePolicy(sizePolicy)
        self.moreTemplatesPushButton.setObjectName("moreTemplatesPushButton")
        self.moreTemplatesVLayout.addWidget(self.moreTemplatesPushButton)
        self.verticalLayout.addLayout(self.moreTemplatesVLayout)
        self.verticalLayout_3.addWidget(self.TemplatesListGroupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.exportPushButton = QtWidgets.QPushButton(text_templates_window)
        self.exportPushButton.setObjectName("exportPushButton")
        self.horizontalLayout_2.addWidget(self.exportPushButton)
        self.applyPushButton = QtWidgets.QPushButton(text_templates_window)
        self.applyPushButton.setObjectName("applyPushButton")
        self.horizontalLayout_2.addWidget(self.applyPushButton)
        self.closePushButton = QtWidgets.QPushButton(text_templates_window)
        self.closePushButton.setObjectName("closePushButton")
        self.horizontalLayout_2.addWidget(self.closePushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(text_templates_window)
        QtCore.QMetaObject.connectSlotsByName(text_templates_window)

    def retranslateUi(self, text_templates_window):
        _translate = QtCore.QCoreApplication.translate
        text_templates_window.setWindowTitle(_translate("text_templates_window", "text_templates_window"))
        self.label.setText(_translate("text_templates_window", "CIF key:"))
        self.combinedTestGroupBox.setTitle(_translate("text_templates_window", "Combined text"))
        self.plainTextEdit.setPlaceholderText(_translate("text_templates_window", "The text of the selected templates is added her in selection order"))
        self.TemplatesListGroupBox.setTitle(_translate("text_templates_window", "Select one or more templates"))
        self.moreTemplatesPushButton.setText(_translate("text_templates_window", "More Templates"))
        self.exportPushButton.setText(_translate("text_templates_window", "Export Templates"))
        self.applyPushButton.setText(_translate("text_templates_window", "Apply"))
        self.closePushButton.setText(_translate("text_templates_window", "Close"))
