# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_ui.ui'
#
# Created by: PyQt5 UI code generator#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CifOrderForm(object):
    def setupUi(self, CifOrderForm):
        CifOrderForm.setObjectName("CifOrderForm")
        CifOrderForm.resize(679, 589)
        self.gridLayout = QtWidgets.QGridLayout(CifOrderForm)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.moveUpPushButton = QtWidgets.QPushButton(CifOrderForm)
        self.moveUpPushButton.setObjectName("moveUpPushButton")
        self.verticalLayout.addWidget(self.moveUpPushButton)
        self.moveDownPushButton = QtWidgets.QPushButton(CifOrderForm)
        self.moveDownPushButton.setObjectName("moveDownPushButton")
        self.verticalLayout.addWidget(self.moveDownPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.addKeyPushButton = QtWidgets.QPushButton(CifOrderForm)
        self.addKeyPushButton.setObjectName("addKeyPushButton")
        self.verticalLayout.addWidget(self.addKeyPushButton)
        self.importCifPushButton = QtWidgets.QPushButton(CifOrderForm)
        self.importCifPushButton.setObjectName("importCifPushButton")
        self.verticalLayout.addWidget(self.importCifPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.saveSettingPushButton = QtWidgets.QPushButton(CifOrderForm)
        self.saveSettingPushButton.setObjectName("saveSettingPushButton")
        self.verticalLayout.addWidget(self.saveSettingPushButton)
        self.restoreDefaultPushButton = QtWidgets.QPushButton(CifOrderForm)
        self.restoreDefaultPushButton.setObjectName("restoreDefaultPushButton")
        self.verticalLayout.addWidget(self.restoreDefaultPushButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.deleteKeyPushButton = QtWidgets.QPushButton(CifOrderForm)
        self.deleteKeyPushButton.setObjectName("deleteKeyPushButton")
        self.verticalLayout.addWidget(self.deleteKeyPushButton)
        self.gridLayout.addLayout(self.verticalLayout, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 3, 1, 1, 1)
        self.cifOrderTableWidget = QtWidgets.QTableWidget(CifOrderForm)
        self.cifOrderTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.cifOrderTableWidget.setProperty("showDropIndicator", False)
        self.cifOrderTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.cifOrderTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.cifOrderTableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.cifOrderTableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.cifOrderTableWidget.setObjectName("cifOrderTableWidget")
        self.cifOrderTableWidget.setColumnCount(1)
        self.cifOrderTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.cifOrderTableWidget.setHorizontalHeaderItem(0, item)
        self.cifOrderTableWidget.horizontalHeader().setStretchLastSection(True)
        self.cifOrderTableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.cifOrderTableWidget, 2, 0, 4, 1)
        self.helpTextLabel = QtWidgets.QLabel(CifOrderForm)
        self.helpTextLabel.setObjectName("helpTextLabel")
        self.gridLayout.addWidget(self.helpTextLabel, 1, 0, 1, 2)

        self.retranslateUi(CifOrderForm)
        QtCore.QMetaObject.connectSlotsByName(CifOrderForm)

    def retranslateUi(self, CifOrderForm):
        _translate = QtCore.QCoreApplication.translate
        CifOrderForm.setWindowTitle(_translate("CifOrderForm", "Form"))
        self.moveUpPushButton.setText(_translate("CifOrderForm", "Move Up"))
        self.moveDownPushButton.setText(_translate("CifOrderForm", "Move Down"))
        self.addKeyPushButton.setWhatsThis(_translate("CifOrderForm", "Add a single or more CIF keywords to the list."))
        self.addKeyPushButton.setText(_translate("CifOrderForm", "Add Key(s)"))
        self.importCifPushButton.setWhatsThis(_translate("CifOrderForm", "<html><head/><body><p>The order of CIF keywords in the imported CIF defines the order in the list and therefore the order in the output CIF of FinalCif.</p></body></html>"))
        self.importCifPushButton.setText(_translate("CifOrderForm", "Import order from CIF "))
        self.saveSettingPushButton.setText(_translate("CifOrderForm", "Save permanently"))
        self.restoreDefaultPushButton.setText(_translate("CifOrderForm", "Restore default"))
        self.deleteKeyPushButton.setText(_translate("CifOrderForm", "Delete selected key"))
        item = self.cifOrderTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CifOrderForm", "CIF key"))
        self.helpTextLabel.setText(_translate("CifOrderForm", "Order of CIF keys in the output file. Enabled forces them to remain in the output CIF."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CifOrderForm = QtWidgets.QWidget()
    ui = Ui_CifOrderForm()
    ui.setupUi(CifOrderForm)
    CifOrderForm.show()
    sys.exit(app.exec_())
