name: publish
on:
  push:
    tags:
      - '*'
jobs:
  tests:
    uses: ./.github/workflows/python_tests.yml
  release-build:
    runs-on: ubuntu-latest
    # Build and publish are gated on successful tests.
    needs:
      - tests

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.14"

      - run: uv build

      - uses: actions/upload-artifact@v7
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    needs:
      - release-build
    name: publish
    runs-on: ubuntu-latest
    environment:
      name: publish
      url: https://pypi.org/p/fastmolwidget
    permissions:
      contents: read
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: release-dists
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
